version: "3.9"

services:
  front:
    build: ./frontend
    ports: 
      - "8080:8080"
    networks:
      - frontend
      - backend
  back:
    build: ./backend
    ports: 
      - 8081:8080
    networks:
      - frontend
      - backend
  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports: 
      - "3306:3306"
      - "33060:33060"
    environment:
      MYSQL_ROOT_PASSWORD: strongpassword
      MYSQL_DATABASE: guestbook
      MYSQL_USER: dbuser
      MYSQL_PASSWORD: stronguserpassword
    networks:
      - backend

networks:
  frontend:
  backend: