version: "3.9"

services:
  front:
    build: orbot90/guestbook-frontend
    ports: 
      - "8081:8081"
  back:
    image: orbot90/guestbook-backend
    ports: 
      - 8080:8080
    links:
      - "db:db"
  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports: 
      - "3306:3306"
      - "33060:33060"
    environment:
      MYSQL_ROOT_PASSWORD: strongpassword
      MYSQL_DATABASE: guestbook
      MYSQL_USER: dbuser
      MYSQL_PASSWORD: stronguserpassword